server:
  port: 80
spring:
  application:
    name: spring-security-one
  session:
    store-type: redis
    # 3600s
    timeout: 3600
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.4:3306/db_security?useSSL=false
    username: root
    password: 123456
  # redis 配置
  redis:
    host: 192.168.8.4
    port: 6379
    database: 0
    password: 123456
    timeout: 60
  security:
    # 简单配置用户
    user:
      name: user
      password: 123456
# 通用mapper配置
mapper:
  identity: mysql
# 分页助手配置
pagehelper:
  helper-dialect: mysql
  # 分页合理化参数
  reasonable: true
#logging:
#  level:
#    root: debug
